name: "fraud_rf"
platform: "onnxruntime_onnx"
max_batch_size: 64
input [
  {
    name: "float_input"
    data_type: TYPE_FP32
    dims: [ 29 ]
  }
]
output [
  {
    name: "probabilities"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]
instance_group [
  {
    kind: KIND_CPU
  }
]
